#!/bin/bash
DOMAIN=$1

curl -n https://api.heroku.com/apps/$HEROKU_APP_NAME/domains \
  -d '{ "hostname": "'$DOMAIN'" }' \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3" \
  -H "Authorization: Bearer $HEROKU_AUTH_TOKEN"
