#!/bin/bash
curl -n https://api.heroku.com/apps/$HEROKU_APP_NAME/acm \
  -d '{}' \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3" \
  -H "Authorization: Bearer $HEROKU_AUTH_TOKEN"
