# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  api_domain: <%= fetch_from_env("API_DOMAIN") %>
  domain: <%= fetch_from_env("DOMAIN") %>
  secret_key_base: <%= fetch_from_env("SECRET_KEY_BASE") %>
  aws_access_key: <%= fetch_from_env("AWS_ACCESS_KEY") %>
  aws_secret_access_key: <%= fetch_from_env("AWS_SECRET_ACCESS_KEY") %>
  aws_region: <%= fetch_from_env("AWS_REGION") %>
  aws_bucket: <%= fetch_from_env("AWS_BUCKET") %>
  intercom_secret_key: <%= fetch_from_env("INTERCOM_SECRET_KEY") %>
  last_privacy_policy_update_at: <%= fetch_from_env("LAST_PRIVACY_POLICY_UPDATE_AT") %>
  mailchimp_api_key: <%= fetch_from_env("MAILCHIMP_API_KEY") %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default

test:
  <<: *default
